import imgApi from '~/public/images/imgAPI';

const testimonialsData = [
  {
    avatar: imgApi.avatar[0],
    name: 'Sayma Zaman',
    title: 'TechSavvy Solutions',
    text: 'Working with Nur was an absolute pleasure. Their dedication to creating a responsive and user-friendly website exceeded our expectations.',
    x: 100,
    y: 150,
  },
  {
    avatar: imgApi.avatar[6],
    name: 'Sazul Hossain',
    title: 'CodeCrafters Inc',
    text: 'I highly recommend Nur for any web development project.',
    x: 120,
    y: 100,
  },
  {
    avatar: imgApi.avatar[7],
    name: 'John Doe',
    title: 'ByteWave Technologies',
    text: "I had the pleasure of working with Nur on a complex web development project, and I couldn't be happier with the results. ",
    x: 400,
    y: 40,
  },
  {
    avatar: imgApi.avatar[8],
    name: 'Sahin Alam',
    title: 'InnovateIT Labs',
    text: 'I highly recommend Nur for any web development project..',
    x: 500,
    y: 300,
  },
  {
    avatar: imgApi.avatar[4],
    name: 'Afzal Hossain',
    title: 'QuantumTech Partners',
    text: "I had the privilege of collaborating with Nur on a complex web development project, and I couldn't be more impressed.",
    x: 270,
    y: 220,
  },
  {
    avatar: imgApi.avatar[9],
    name: 'Ziaul Haq',
    title: 'CyberNest Innovations',
    text: 'Hiring Nur as our web developer was a game-changer for our business. Their talent in creating custom web solutions, optimizing site performance, and ensuring a seamless user experience made a substantial impact on our online presence.',
    x: 100,
    y: 200,
  },
  {
    avatar: imgApi.avatar[6],
    name: 'Ali Ahmed',
    title: 'DataPulse Systems',
    text: "We couldn't have asked for a better web developer than Nur. Their technical prowess, creative problem-solving, and commitment to delivering a top-tier website were evident in every aspect of our project. ",
    x: 100,
    y: 40,
  },
  {
    avatar: imgApi.avatar[10],
    name: 'Haniya Rahman',
    title: 'InfraGenius Services',
    text: "I can't say enough about the exceptional web development services provided by Nur. Their ability to transform our ideas into a visually stunning and functional website was impressive",
    x: 330,
    y: 100,
  },
  {
    avatar: imgApi.avatar[1],
    name: 'Tahmiha Rahman',
    title: 'SoftEdge Innovations',
    text: "I had the pleasure of working with Nur on a challenging e-commerce project. Their technical prowess, commitment to meeting deadlines, and proactive approach to problem-solving were instrumental in the project's success.",
    x: 30,
    y: 50,
  },
  {
    avatar: imgApi.avatar[9],
    name: 'Fahim Ahmed',
    title: 'LogicLink IT Solutions',
    text: "If you're in search of a top-notch web developer, look no further than Nur. Their deep knowledge of web technologies, dedication to crafting responsive designs, and commitment to delivering projects on time are second to none",
    x: 400,
    y: 150,
  },
  {
    avatar: imgApi.avatar[8],
    name: 'Raiyan Hasan',
    title: 'NetMasters Consulting',
    text: 'Nur is a web development wizard! They consistently impressed us with their ability to turn our ideas into reality. Their attention to detail and expertise in creating dynamic, user-friendly websites is truly remarkable. Working with Nur was a delightful experience.',
    x: 480,
    y: 100,
  },
  {
    avatar: imgApi.avatar[2],
    name: 'Shrikant Paliwal',
    title: 'AppWizards Technologies',
    text: "I've had the privilege of collaborating with Nur on several web development projects, and each experience has been exceptional. Their creative problem-solving, ability to juggle multiple technologies, and excellent communication skills make them a standout web developer.",
    x: 250,
    y: 100,
  },
  {
    avatar: imgApi.avatar[2],
    name: 'Ariya Khan',
    title: 'SystemSculpt IT',
    text: "Working with Nur was a game-changer for our startup. Their web development expertise, ability to provide elegant solutions, and commitment to delivering projects with precision have significantly elevated our online presence. We're extremely satisfied with the results and look forward to many more successful projects with Nur.",
    x: 150,
    y: 300,
  },
  {
    avatar: imgApi.avatar[7],
    name: 'Mitchel Conven',
    title: 'CodeHive Labs',
    text: "Working with Nur was a game-changer for our startup. Their web development expertise, ability to provide elegant solutions, and commitment to delivering projects with precision have significantly elevated our online presence. We're extremely satisfied with the results and look forward to many more successful projects with Nur.",
    x: 300,
    y: 140,
  },
];

export default testimonialsData;
